"""Generate exclusion witnesses; Lean checks every witness in its kernel.

This generator is not part of the proof's trust boundary.
"""
from math import isqrt
from pathlib import Path

LIMIT = 12167
BLOCK = 128


def obstruction(n):
    for p in range(2, isqrt(n) + 1):
        if n % p == 0:
            exponent = 0
            while n % p == 0:
                n //= p
                exponent += 1
            if exponent == 1:
                return p
    return n if n > 1 else None


def code(n):
    for tag, m in [(0, n), (1, n + 1)]:
        r = isqrt(m)
        if r * r == m:
            return 4 * r + tag
    witnesses = [(p, tag) for tag, m in [(2, n), (3, n + 1)]
                 if (p := obstruction(m)) is not None]
    if not witnesses:
        raise RuntimeError(f"Unexpected counterexample below {LIMIT}: {n}")
    p, tag = min(witnesses)
    return 4 * p + tag


def render():
    codes = [code(n) for n in range(LIMIT)]
    lines = [
        "/- Generated by scripts/generate_certificates.py. All data are checked in Lean. -/",
        "import JSP301.Theory", "", "namespace JSP301", "",
        "def certificateBlock : ℕ → List ℕ",
    ]
    count = (LIMIT + BLOCK - 1) // BLOCK
    for b in range(count):
        block = codes[b * BLOCK:(b + 1) * BLOCK]
        lines.append(f"  | {b} => [{', '.join(map(str, block))}]")
    lines.extend(["  | _ => []", "", "set_option maxRecDepth 100000", "set_option maxHeartbeats 0", "",
                  f"theorem block_checked (b : Fin {count}) :",
                  "    checkBlock (b.val * 128) (certificateBlock b.val) = true := by",
                  "  fin_cases b <;> decide +kernel", "",
                  f"theorem block_length (b : Fin {count}) :",
                  f"    (certificateBlock b.val).length = min 128 ({LIMIT} - b.val * 128) := by",
                  "  fin_cases b <;> decide +kernel", "", "end JSP301", ""])
    return "\n".join(lines)


def render_primes():
    primes = sorted({code(n) // 4 for n in range(LIMIT) if code(n) % 4 in (2, 3)})
    lines = ["/- Generated prime pool; every entry has a norm_num proof. -/",
             "import Mathlib.Data.Nat.Prime.Basic", "import Mathlib.Tactic.NormNum.Prime",
             "", "namespace JSP301", "", "set_option maxHeartbeats 0", "set_option maxRecDepth 10000", "",
             f"def primeWitnesses : List ℕ := [{', '.join(map(str, primes))}]", "",
             "theorem primeWitnesses_all : ∀ p ∈ primeWitnesses, p.Prime := by",
             "  unfold primeWitnesses",
             "  simp only [List.forall_mem_cons]",
             "  exact " + "⟨by norm_num, " * len(primes) + "List.forall_mem_nil _" + "⟩" * len(primes),
             "", "theorem primeWitnesses_sound (p : ℕ) (hp : p ∈ primeWitnesses) : p.Prime :=",
             "  primeWitnesses_all p hp", "", "end JSP301", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[1] / "JSP301" / "Certificates.lean"
    target.write_text(render(), encoding="utf-8", newline="\n")
    (target.parent / "PrimeTable.lean").write_text(render_primes(), encoding="utf-8", newline="\n")
    print(f"Generated {LIMIT} exclusion certificates in {(LIMIT + BLOCK - 1) // BLOCK} blocks.")
